2018-05-12 20:16:32.281036: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-05-12 20:16:32.295436: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-05-12 20:16:32.295521: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: arco
2018-05-12 20:16:32.295540: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: arco
2018-05-12 20:16:32.295601: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 367.57.0
2018-05-12 20:16:32.295660: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
"""
2018-05-12 20:16:32.295707: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 367.57.0
2018-05-12 20:16:32.295724: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 367.57.0
Gaussian 128 FCN from FCN_64-128-256_1_cat1-32|1-32|1-32_weight_G_x1_p0_e25_r0-19
On train set
mu =  [ 140.42133132  186.22724995  365.92096392  358.74944958 2449.2505917
 1352.83568307  708.04858695]  in  (7, 128, 128)
class weight [neg= 0.014629, pos= 0.985371]
std =  [113.04792058 135.17366614 230.99671408 248.71498611 952.23666562
 825.62200511 523.41884702]  in  (7, 128, 128)
true_pos  = 7965371
false_pos = 107649715
true_neg  = 519508533
false_neg = 1345629
size = 38847
pos_recall    = 0.8554796477284932
pos_precision = 0.06889560243029184
pos_F1        = 0.12752134089912975
neg_recall    = 0.8283531862280475
neg_precision = 0.9974164956370263
neg_F1        = 0.9050573468974955
accuracy      = 13578.240378922439
balanced_accuracy = 0.8419164169782704
balanced_acc =  0.8419164169782704 AUC =  0.9207755994945384 avg_precision =  0.2000061385040459
xen =  0.010216276703151774
On cv set
mu =  [ 145.02183288  190.77598344  361.33590698  366.91707464 2380.64990791
 1375.52599508  734.46670819]  in  (7, 128, 128)
class weight [neg= 0.025683, pos= 0.974317]
std =  [120.35045017 142.82855956 224.8264348  259.40579968 811.03520645
 842.84666761 560.72898821]  in  (7, 128, 128)
true_pos  = 119836
false_pos = 1329809
true_neg  = 4448872
false_neg = 32491
size = 362
pos_recall    = 0.7867022917801835
pos_precision = 0.08266575609890697
pos_F1        = 0.14961060492942452
neg_recall    = 0.769876724463593
neg_precision = 0.9927497504665433
neg_F1        = 0.8672227916371509
accuracy      = 12620.740331491712
balanced_accuracy = 0.7782895081218882
balanced_acc =  0.7782895081218882 AUC =  0.8622603468520593 avg_precision =  0.19585482835072815
xen =  0.02383390135126631
On test set
mu =  [ 185.232605    238.7054643   430.14717078  446.99416135 2409.52013496
 1646.65212952  922.71874759]  in  (7, 128, 128)
class weight [neg= 0.012677, pos= 0.987323]
std =  [120.14719703 144.63647815 226.45236114 262.10519119 820.82781844
 841.09542711 571.9831284 ]  in  (7, 128, 128)
true_pos  = 1284939
false_pos = 29976343
true_neg  = 89388528
false_neg = 247726
size = 7379
pos_recall    = 0.8383691152339227
pos_precision = 0.04110320875516238
pos_F1        = 0.07836440060112314
neg_recall    = 0.748867964679491
neg_precision = 0.9972363191348893
neg_F1        = 0.8553880080789039
accuracy      = 12288.042688711208
balanced_accuracy = 0.7936185399567068
balanced_acc =  0.7936185399567068 AUC =  0.8742644144840251 avg_precision =  0.11740889945888935
xen =  0.011620424043421
/localdata/u6142160/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/localdata/u6142160/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
