2018-05-12 03:26:22.505888: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-05-12 03:26:22.521873: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-05-12 03:26:22.522007: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: arco
2018-05-12 03:26:22.522035: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: arco
2018-05-12 03:26:22.522125: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 367.57.0
2018-05-12 03:26:22.522203: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
"""
2018-05-12 03:26:22.522270: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 367.57.0
2018-05-12 03:26:22.522296: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 367.57.0
Gaussian 128 FCN from FCN_64-128-256_1_cat1-32;3-32|1-32;3-32_weight_G_x1_p0_e25_r0-13
On train set
mu =  [ 140.42133132  186.22724995  365.92096392  358.74944958 2449.2505917
 1352.83568307  708.04858695]  in  (7, 128, 128)
class weight [neg= 0.014629, pos= 0.985371]
std =  [113.04792058 135.17366614 230.99671408 248.71498611 952.23666562
 825.62200511 523.41884702]  in  (7, 128, 128)
true_pos  = 7503534
false_pos = 107163486
true_neg  = 519994762
false_neg = 1807466
size = 38847
pos_recall    = 0.8058784233702073
pos_precision = 0.06543759487252743
pos_F1        = 0.12104619835032047
neg_recall    = 0.8291284754019531
neg_precision = 0.996536109079243
neg_F1        = 0.9051569185570488
accuracy      = 13578.868278116714
balanced_accuracy = 0.8175034493860802
balanced_acc =  0.8175034493860802 AUC =  0.9018326887977931 avg_precision =  0.1700744233344021
xen =  0.011404512655045489
On cv set
mu =  [ 145.02183288  190.77598344  361.33590698  366.91707464 2380.64990791
 1375.52599508  734.46670819]  in  (7, 128, 128)
class weight [neg= 0.025683, pos= 0.974317]
std =  [120.35045017 142.82855956 224.8264348  259.40579968 811.03520645
 842.84666761 560.72898821]  in  (7, 128, 128)
true_pos  = 119012
false_pos = 1259116
true_neg  = 4519565
false_neg = 33315
size = 362
pos_recall    = 0.781292876509089
pos_precision = 0.08635772584259227
pos_F1        = 0.15552499093406863
neg_recall    = 0.7821101389746207
neg_precision = 0.9926826536170512
neg_F1        = 0.8749045763752447
accuracy      = 12813.74861878453
balanced_accuracy = 0.7817015077418548
balanced_acc =  0.7817015077418548 AUC =  0.8675851392987095 avg_precision =  0.19835370085488357
xen =  0.022884757410752903
On test set
mu =  [ 185.232605    238.7054643   430.14717078  446.99416135 2409.52013496
 1646.65212952  922.71874759]  in  (7, 128, 128)
class weight [neg= 0.012677, pos= 0.987323]
std =  [120.14719703 144.63647815 226.45236114 262.10519119 820.82781844
 841.09542711 571.9831284 ]  in  (7, 128, 128)
true_pos  = 1277794
false_pos = 28851319
true_neg  = 90513552
false_neg = 254871
size = 7379
pos_recall    = 0.8337073006821452
pos_precision = 0.04241060797242853
pos_F1        = 0.08071523968110698
neg_recall    = 0.7582930492171353
neg_precision = 0.997192074164382
neg_F1        = 0.861487014047379
accuracy      = 12439.537335682342
balanced_accuracy = 0.7960001749496401
balanced_acc =  0.7960001749496401 AUC =  0.8769369597791411 avg_precision =  0.109557030980958
xen =  0.01123205480849978
/localdata/u6142160/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/localdata/u6142160/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
