2018-05-12 10:06:10.656673: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2018-05-12 10:06:10.674876: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-05-12 10:06:10.675016: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: arco
2018-05-12 10:06:10.675043: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: arco
2018-05-12 10:06:10.675158: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 367.57.0
2018-05-12 10:06:10.675241: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 
"""
2018-05-12 10:06:10.675308: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 367.57.0
2018-05-12 10:06:10.675333: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 367.57.0
Gaussian 128 FCN from FCN_32-64-128_1_cat1-32;3-32_weight_G_x1_p0_e25_r0-21
On train set
mu =  [ 140.42133132  186.22724995  365.92096392  358.74944958 2449.2505917
 1352.83568307  708.04858695]  in  (7, 128, 128)
class weight [neg= 0.014629, pos= 0.985371]
std =  [113.04792058 135.17366614 230.99671408 248.71498611 952.23666562
 825.62200511 523.41884702]  in  (7, 128, 128)
true_pos  = 7321338
false_pos = 137594977
true_neg  = 489563271
false_neg = 1989662
size = 38847
pos_recall    = 0.7863106003651595
pos_precision = 0.050521143875346265
pos_F1        = 0.09494217026341929
neg_recall    = 0.7806056486719442
neg_precision = 0.995952293504065
neg_F1        = 0.8752272781655519
accuracy      = 12790.810332844236
balanced_accuracy = 0.7834581245185519
balanced_acc =  0.7834581245185519 AUC =  0.8677945261120734 avg_precision =  0.1289413760518199
xen =  0.01308220979661243
On cv set
mu =  [ 145.02183288  190.77598344  361.33590698  366.91707464 2380.64990791
 1375.52599508  734.46670819]  in  (7, 128, 128)
class weight [neg= 0.025683, pos= 0.974317]
std =  [120.35045017 142.82855956 224.8264348  259.40579968 811.03520645
 842.84666761 560.72898821]  in  (7, 128, 128)
true_pos  = 122391
false_pos = 1600985
true_neg  = 4177696
false_neg = 29936
size = 362
pos_recall    = 0.803475418015191
pos_precision = 0.07101816434718831
pos_F1        = 0.13050147064860482
neg_recall    = 0.7229497527203872
neg_precision = 0.9928853093616552
neg_F1        = 0.8366843698970781
accuracy      = 11878.693370165745
balanced_accuracy = 0.7632125853677891
balanced_acc =  0.7632125853677891 AUC =  0.8492326023562793 avg_precision =  0.1750758587759226
xen =  0.02413512074494045
On test set
mu =  [ 185.232605    238.7054643   430.14717078  446.99416135 2409.52013496
 1646.65212952  922.71874759]  in  (7, 128, 128)
class weight [neg= 0.012677, pos= 0.987323]
std =  [120.14719703 144.63647815 226.45236114 262.10519119 820.82781844
 841.09542711 571.9831284 ]  in  (7, 128, 128)
true_pos  = 1333040
false_pos = 37846650
true_neg  = 81518221
false_neg = 199625
size = 7379
pos_recall    = 0.8697530119106263
pos_precision = 0.03402375057076766
pos_F1        = 0.06548577207091066
neg_recall    = 0.6829330967902608
neg_precision = 0.997557143148389
neg_F1        = 0.8107929136445874
accuracy      = 11227.979536522564
balanced_accuracy = 0.7763430543504435
balanced_acc =  0.7763430543504435 AUC =  0.8665921396460311 avg_precision =  0.09330180967721045
xen =  0.011824178932668059
/localdata/u6142160/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/localdata/u6142160/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
